name: call workflow
on: pull_request
jobs:
  call:
    uses: .github/workflows/reusable-workflows.yaml
    with:
      pr-number: ${{ github.event.pull_request.event }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
  # print:
  #   needs: [call]
  #   runs-on: ubuntu-latest
