name: Reusable workflows
on:
  workflow_call:
    inputs:
      pr-number:
        type: string
        default: ${{ github.event.pull_request.number }}
        required: false
    secrets:
      token:
        required: true
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: pr-comment
        run: |
          body="Welcome, ${{ github.actor }}"
          gh pr comment "${PR_NUMBER}" --body "${body}"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
          echo ${{ github.event.pull_request }}
        env:
          PR_NUMBER: ${{ inputs.pr-number }}
          GITHUB_TOKEN: ${{ secrets.token }}
