name: Status Check Example
on:
  push:
jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "hello"
      - run: echo "helllo"
        if: ${{ failure() }}
